version: "3.9"

services:

  backend:
    build: ./backend
    container_name: sales-backend
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: sales-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend